In [6]:
import numpy as np

u = np.eye(5, k=-2)
print(u)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [4]:

l1 = [1, 2, 3]
l2 = [4, 5, 6]

ff = np.stack((l1, l2))

print(ff)

[[1 2 3]
 [4 5 6]]


In [3]:
ff

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.stack((arr,aee1))

NameError: name 'arr' is not defined

In [ ]:
import pandas as pd
import matplotlib as plt
